# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool: dts-build-agent

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildandPush
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to Azure container registry
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'Azure Container Registry - DTS'
        Dockerfile: '**/Dockerfile'
        repository: 'next-template'
        tags: 'azure-$(Build.BuildId)-dev'