version: "3"

services:
  db:
    image: deadrobots/pixi:datastore
    container_name: pixidb
    ports:
      - "27017:27017"
      - "28017:28017"
    expose:
      - "27017"
      - "28017"

  app:
    build: ./
    ports:
      - "3000:3000"
      - "8090:8090"