name: Load Test
on:   
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.2.0
        with:
          cloud: true
          filename: load-test.js
          flags: --vus 50 --duration 10s
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          
