# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test (Unit, Lint, E2E)

on:
  pull_request:
    branches: [ main ]

jobs:

  linting_script:
  #Linting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: linting
      run: |
        npm ci 
        npm run lint --if-present
  
  build_and_unit_test:
  #Runs Unit Tests
    needs: linting_script
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: "Building and Unit Tests Against Node"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run test:ci --if-present

  build_and_e2e_test:
    #Runs Cypress Tests, IF cypress has been setup
    needs: build_and_unit_test
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm ci
    - name: Cypress E2E Tests
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
        wait-on: http://localhost:3000
        
