# This is a basic workflow to help you get started with Actions

name: Security - ZAP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# We have many jobs
jobs:
    deploy:
      name: Deploy and test Pixi
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Install
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          NEXT_CMS_URL: ${{ secrets.NEXT_CMS_URL }}
          CI: true

      - name: Start
        run: npm run start
        env:
          CI: true

      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:3000'
          fail_action: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
